apiVersion: v1
kind: Service
metadata:
  name: vpa-operator-registry
spec:
  type: ClusterIP
  selector:
    registry.operator.verticalpodautoscaler: "true"
  ports:
  - name: grpc
    port: 50051
    protocol: TCP
    targetPort: 50051
  sessionAffinity: None

